import { ComboModel } from '../model/ComboModel'

/**
 * 套餐数据
 */
export const ComboData: Array<ComboModel> =
  [
    {
      comboName: '【人气】近期热销组合，建议1人食用',
      comboType: '1',
      price: 29.3,
      comboGoods: [
        {
          name: '金色山脉珍珠奶茶',
          image: 'combo_01_01',
          price: 17,
        },
        {
          name: '紫薯芋泥双料包',
          image: 'combo_01_02',
          price: 10.8,
        }
      ]
    },
    {
      comboName: '近期热销组合',
      comboType: '2',
      price: 30.6,
      comboGoods: [
        {
          name: '南瓜嘟嘟',
          image: 'combo_02_01',
          price: 14.8,
        },
        {
          name: '松松咸蛋黄嘟嘟',
          image: 'combo_02_02',
          price: 14.8,
        }
      ]
    },
    {
      comboName: '近期热销组合，建议1人食用',
      comboType: '2',
      price: 32.3,
      comboGoods: [
        {
          name: '霸气杨枝甘露',
          image: 'combo_03_01',
          price: 20,
        },
        {
          name: '紫薯芋泥双料包',
          image: 'combo_01_02',
          price: 10.8,
        }
      ]
    },
    {
      comboName: '近期同品牌热销191单',
      comboType: '2',
      price: 48,
      comboGoods: [
        {
          name: '超能牛油果酸奶昔',
          image: 'combo_04_01',
          price: 20,
        },
        {
          name: '浓抹黑珍珠',
          image: 'combo_04_02',
          price: 26,
        }
      ]
    },
    {
      comboName: '近期热销组合，建议1人食用',
      comboType: '2',
      price: 43,
      comboGoods: [
        {
          name: '浓抹黑珍珠',
          image: 'combo_04_02',
          price: 26,
        },
        {
          name: '金色山脉珍珠奶茶',
          image: 'combo_01_01',
          price: 17,
        },
      ]
    },
  ]