import { EvalTypeModel } from '../model/EvalTypeModel'

/**
 * 外卖详情页评价类型数据
 */
export const EvalTypeData: Array<EvalTypeModel> =
  [
    {
      name: "全部",
      count: 1057,
    },
    {
      name: "有图评价",
      count: 95,
    },
    {
      name: "好评",
      count: 1023,
    },
    {
      name: "中评",
      count: 12,
    },
    {
      name: "差评",
      count: 22,
      isBad: true,
    },
    {
      name: "味道赞",
      count: 23,
    },
    {
      name: "服务好",
      count: 13,
    },
    {
      name: "推荐",
      count: 9,
    },
    {
      name: "满意",
      count: 4,
    },
    {
      name: "包装差",
      count: 4,
      isBad: true,
    },
    {
      name: "分量足",
      count: 3,
    },

  ]