import { HomeGoodsModel } from '../model/HomeGoodsModel'

/**
 * 首页店铺数据
 */
export const HomeGoodsData: Array<HomeGoodsModel> = [
  {
    title: '华莱士.全鸡汉堡',
    image: 'goods_01',
    type: '外卖',
    time: '15分钟',
    activity: ['可用20元券', '27减1', '1.37折起'],
    score: '4.7分',
    turnover: '月售1000+'
  },
  {
    title: '花之悦螺蛳粉',
    image: 'goods_02',
    type: '外卖',
    time: '49分钟',
    activity: ['120减1', '7.48折起'],
    score: '4.8分',
    turnover: '月售700+'
  },
  {
    title: '思思味黄焖鸡米饭',
    image: 'goods_03',
    type: '外卖',
    time: '40分钟',
    activity: ['可用12元券', '149减1', '9.97折起'],
    score: '4.5分',
    turnover: '月售500+'
  },
  {
    title: '福满笼（小笼包、馄饨）',
    image: 'goods_04',
    type: '外卖',
    time: '15分钟',
    activity: ['6.39折起'],
    score: '4.6分',
    turnover: '月售900+'
  },
  {
    title: '丫丫炒粉（炒米线、炒河粉）',
    image: 'goods_05',
    type: '外卖',
    time: '40分钟',
    activity: ['可用12元券', '130减1', '9.67折起'],
    score: '4.5分',
    turnover: '月售800+'
  },
  {
    title: '三只熊披萨',
    image: 'goods_06',
    type: '外卖',
    time: '40分钟',
    activity: ['可用12元券', '6.31折起'],
    score: '4.8分',
    turnover: '月售900+'
  },
  {
    title: '逍遥镇胡辣汤',
    image: 'goods_07',
    type: '外卖',
    time: '15分钟',
    activity: ['37减2', '9.31折起', '79减5'],
    score: '4.3分',
    turnover: '月售500+'
  },
  {
    title: '杨小哥擀面皮•西安肉夹馍',
    image: 'goods_08',
    type: '外卖',
    time: '40分钟',
    activity: ['可用12元券', '48减2', '58减3'],
    score: '4.6分',
    turnover: '月售400+'
  },
  {
    title: '滋麻官火锅米线',
    image: 'goods_09',
    type: '外卖',
    time: '28分钟',
    activity: ['39减2', '9.37折起', '80减5'],
    score: '4.1分',
    turnover: '月售200+'
  },
  {
    title: '好佳香川菜馆',
    image: 'goods_10',
    type: '外卖',
    time: '15分钟',
    activity: ['50减1', '60减3', '100减5'],
    score: '4.9分',
    turnover: '月售1000+'
  }
]
