import { HomeGridModel } from '../model/HomeGridModel'

/**
 * 首页宫格数据
 */
export const HomeGridData: Array<Array<HomeGridModel>> = [
  [
    {
      title: "外卖",
      uri: "grid_wm"
    },
    {
      title: "超市便利",
      uri: "grid_csbl"
    },
    {
      title: "酒店民宿",
      uri: "grid_jdms"
    },
    {
      title: "休闲玩乐",
      uri: "grid_xxwl"
    },
    {
      title: "看病买药",
      uri: "grid_kbmy"
    },
    {
      title: "美食",
      uri: "grid_ms"
    },
    {
      title: "跑腿",
      uri: "grid_pt"
    },
    {
      title: "生活服务",
      uri: "grid_shfw"
    },
    {
      title: "打车",
      uri: "grid_dc"
    },
    {
      title: "电影演出",
      uri: "grid_dyyc"
    },
    {
      title: "民宿公寓",
      uri: "grid_msgy"
    },
    {
      title: "骑车",
      uri: "grid_qc"
    },
    {
      title: "景点游玩",
      uri: "grid_jdyw"
    },
    {
      title: "按摩足疗",
      uri: "grid_amzl"
    },
    {
      title: "丽人美发",
      uri: "grid_lrmf"
    },
  ],
  [
    {
      title: "洗浴汗蒸",
      uri: "grid_xyhz"
    },
    {
      title: "蔬菜水果",
      uri: "grid_scsg"
    },
    {
      title: "浪漫鲜花",
      uri: "grid_lmxh"
    },
    {
      title: "旅游度假",
      uri: "grid_lydj"
    },
    {
      title: "品质百货",
      uri: "grid_pzbh"
    },
    {
      title: "特价团",
      uri: "grid_tjt"
    },
    {
      title: "甜品饮品",
      uri: "grid_tpyp"
    },
    {
      title: "手机数码",
      uri: "grid_sjsm"
    },
    {
      title: "服饰百货",
      uri: "grid_fsbh"
    },
    {
      title: "天天红包",
      uri: "grid_tthb"
    }
  ]
]