import { HomeGridModel } from '../model/HomeGridModel'

/**
 * 外卖页 宫格数据
 */
export const TakeoutGridData: Array<Array<HomeGridModel>> = [
  [
    {
      title: "美食",
      uri: "take_ms"
    },
    {
      title: "甜点饮品",
      uri: "take_tdyp"
    },
    {
      title: "超市便利",
      uri: "take_csbl"
    },
    {
      title: "蔬菜水果",
      uri: "take_scsg"
    },
    {
      title: "看病买药",
      uri: "take_kbmy"
    },
    {
      title: "晚餐",
      uri: "take_wc"
    },
    {
      title: "拼好饭",
      uri: "take_phf"
    },
    {
      title: "跑腿",
      uri: "take_pt"
    },
    {
      title: "天天津贴",
      uri: "take_ttjt"
    },
    {
      title: "汉堡披萨",
      uri: "take_hbps"
    },
    {
      title: "黄焖鸡米饭",
      uri: "take_hmjmf"
    },
    {
      title: "品质百货",
      uri: "take_pzbh"
    },
    {
      title: "小吃馆",
      uri: "take_xcg"
    },
    {
      title: "必点榜",
      uri: "take_bdb"
    },
    {
      title: "浪漫鲜花",
      uri: "take_lmxh"
    }
  ],
  [
    {
      title: "买酒",
      uri: "take_mj"
    },
    {
      title: "快食简餐",
      uri: "take_ksjc"
    },
    {
      title: "日韩料理",
      uri: "take_rhll"
    },
    {
      title: "麻辣烫冒菜",
      uri: "take_mltmc"
    },
    {
      title: "家常菜",
      uri: "take_jcc"
    },
    {
      title: "煲仔饭",
      uri: "take_bzf"
    },
    {
      title: "凉皮肉夹馍",
      uri: "take_lprjm"
    },
    {
      title: "饺子馆",
      uri: "take_jzg"
    },

  ]
]