import { TypeModel } from '../model/TypeModel'

/**
 * 外卖详情页 左侧分类数据
 */
export const TypeData: Array<TypeModel> =
  [
    {
      title: "推荐",
      image: "icon_recomm"
    },
    {
      title: "折扣",
      image: "icon_discount"
    },
    {
      title: "生可可黑茶",
    },
    {
      title: "每日蔬果瓶",
    },
    {
      title: "霸气鲜果茶",
    },
    {
      title: "蔬果酸奶昔",
    },
    {
      title: "暖香鲜乳茶",
    },
    {
      title: "纯茶咖啡",
    },
    {
      title: "软欧面包",
    },
    {
      title: "蛋糕甜点",
    },
    {
      title: "零食茶叶",
    },
  ]